### ISSUE TITLE
Monitor stops abruptly and sync progress never triggers

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#868] opened 2023-01-05 11:18 UTC
### Describe the bug

While generating a free atSign, monitor suddenly stops.
Attaching the logs.

```
flutter: _checkRootLocation error: Exception: Unable to find secondary address for atSign:senegallevel31
flutter: INFO|2023-01-05 15:57:23.722571|AtLookup|Creating new connection
flutter: INFO|2023-01-05 15:57:29.419452|AtLookup|Creating new connection
flutter: INFO|2023-01-05 15:57:35.379365|AtLookup|from result:data:_41d5a58d-fd46-4bf5-9db5-a672916f0580@senegallevel31:21964b19-c9a2-4597-b438-bb4c8c288937
flutter: INFO|2023-01-05 15:57:35.794977|AtLookup|auth success
flutter: INFO|2023-01-05 15:57:43.003416|HiveBase|commit_log_99b48cfe8fc887d09f109e6334698e071fc1932864a01bd688cb7e7c3aabb43d initialized successfully
flutter: INFO|2023-01-05 15:57:50.019417|HiveBase|99b48cfe8fc887d09f109e6334698e071fc1932864a01bd688cb7e7c3aabb43d initialized successfully
flutter: INFO|2023-01-05 15:57:50.026954|Monitor|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback
flutter: INFO|2023-01-05 15:57:55.016430|AtLookup|Creating new connection

flutter: INFO|2023-01-05 15:58:15.052146|AtLookup|auth success
flutter: INFO|2023-01-05 15:58:15.372332|SyncService|Returning the serverCommitId 1
flutter: INFO|2023-01-05 15:58:15.733834|SyncService|Returning the serverCommitId 1
flutter: INFO|2023-01-05 15:58:16.397489|SyncService|Inside syncComplete. syncRequest.requestSource : [SyncRequestSource.app](http://syncrequestsource.app/) ; syncRequest.onDone : null
flutter: INFO|2023-01-05 15:58:16.775861|SyncService|Returning the serverCommitId 2
flutter: INFO|2023-01-05 15:58:21.651813|Monitor|monitor started for @senegallevel31 with last notification time: null
flutter: INFO|2023-01-05 15:58:24.047277|Monitor|status is MonitorStatus.stopped : heartbeat will not be sent
flutter: error in getting firstname: Exception: public:firstname.wavi@senegallevel31 does not exist in keystore
```

While running it, I was using at_client from **switch_atsign_bug** branch.(There is a fix added by Murali on removeSynListener)

I could also reproduce this with at_client "3.0.49" hosted version.

### Steps to reproduce

1. generate a new atSign
2. save the backup key
3. proceed to the app
4. monitor gets started and stops.
5. syncProgress never gets triggered.

### Expected behavior

Monitor should not stop and sync progress should get triggered.

### Were you using an atApplication when the bug was found?

Buzz

### Additional context

Surprisingly, If we do not save the backup key we do not experience this issue.

**Comment by sachins-geekyants** [comment] 2023-01-05 11:19
Attaching log for another atSign

```
flutter: _checkRootLocation error: Exception: Unable to find secondary address for atSign:crowdedscorpion
flutter: INFO|2023-01-05 16:46:03.682448|AtLookup|Creating new connection
flutter: INFO|2023-01-05 16:46:06.618708|AtLookup|New connection created OK
flutter: INFO|2023-01-05 16:46:07.183496|AtLookup|Creating new connection
flutter: INFO|2023-01-05 16:46:09.235780|AtLookup|New connection created OK
flutter: INFO|2023-01-05 16:46:09.618878|AtLookup|from result:data:_59a5aaf6-9e25-42e1-91cd-f5facff29fd5@crowdedscorpion:13d58eaf-751e-4a6b-98fc-c26aecd296d7
flutter: INFO|2023-01-05 16:46:09.962710|AtLookup|auth success
flutter: INFO|2023-01-05 16:46:11.577079|HiveBase|commit_log_c6936ee7967cb8fbf70d837f5901c39ffa2bda9db98accb115b66cc961685d82 initialized successfully
flutter: INFO|2023-01-05 16:46:11.595145|HiveBase|c6936ee7967cb8fbf70d837f5901c39ffa2bda9db98accb115b66cc961685d82 initialized successfully
flutter: INFO|2023-01-05 16:46:11.608222|Monitor|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback
flutter: INFO|2023-01-05 16:46:15.015217|AtLookup|Creating new connection
flutter: INFO|2023-01-05 16:46:17.011667|AtLookup|New connection created OK
flutter: INFO|2023-01-05 16:46:17.674950|AtLookup|auth success
flutter: INFO|2023-01-05 16:46:18.146385|SyncService|Returning the serverCommitId 1
flutter: INFO|2023-01-05 16:46:18.524916|SyncService|Returning the serverCommitId 1
flutter: INFO|2023-01-05 16:46:19.448507|SyncService|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.app ; syncRequest.onDone : null
flutter: INFO|2023-01-05 16:46:19.776937|SyncService|Returning the serverCommitId 2
flutter: INFO|2023-01-05 16:46:33.637591|AtContactsImpl|atconnections.groupslist.crowdedscorpion.at_contact.mospherepro does not exist in keystore
flutter: INFO|2023-01-05 16:46:33.638480|AtContactsImpl|atconnections.groupslist.crowdedscorpion does not exist in keystore
flutter: INFO|2023-01-05 16:46:33.711188|AtContactsImpl|atconnections.groupslist.crowdedscorpion.at_contact.mospherepro does not exist in keystore
flutter: INFO|2023-01-05 16:46:33.713614|AtContactsImpl|atconnections.groupslist.crowdedscorpion.at_contact.mospherepro does not exist in keystore
flutter: INFO|2023-01-05 16:46:33.715305|AtContactsImpl|atconnections.groupslist.crowdedscorpion does not exist in keystore
flutter: INFO|2023-01-05 16:46:33.717240|AtContactsImpl|atconnections.groupslist.crowdedscorpion does not exist in keystore
flutter: INFO|2023-01-05 16:46:35.019866|Monitor|monitor started for @crowdedscorpion with last notification time: null
flutter: INFO|2023-01-05 16:46:55.227089|Monitor|status is MonitorStatus.stopped : heartbeat will not be sent
```

**Comment by gkc** [comment] 2023-01-05 11:28
This log line `flutter: INFO|2023-01-05 15:57:50.026954|Monitor|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback` shows that something is going on with the network, as the Monitor's onDone is called by the Dart core network handling code (socket listen method)

@sachins-geekyants :
> Surprisingly, If we do not save the backup key we do not experience this issue.

This strongly suggests that this problem is _triggered_ (not necessarily caused, but possibly so) in some way by the code which is saving the backup key. Have you tried to figure out why that is? If you have tried, do you have a hypothesis? If you haven't tried to figure it out, please can you try?

**Comment by gkc** [comment] 2023-01-05 11:39
CORRECTION to my previous comment where I wrote
> This log line `flutter: INFO|2023-01-05 15:57:50.026954|Monitor|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback` shows that something is going on with the network, as the Monitor's onDone is called by the Dart core network handling code (socket listen method)

socket listen will also call onDone if the socket is closed, which is done when Monitor.stop() is called.

@sachins-geekyants Can you rerun all of this with log level set to FINEST please, so we can see a bit more information about what is going on?

**Comment by sachins-geekyants** [comment] 2023-01-05 12:26
In the attached log, I am logged in as `@buzkashipanicky` and then generated a new atSign `@20banzai `.
After atSign generation, I backed up the key -> proceeded to the app (till this time sync progress did not get triggered).

After some time I shared a persona with `@20banzai` which I received and syncProgressListener got triggered.

[monitor_logs.txt](https://github.com/atsign-foundation/at_client_sdk/files/10352064/monitor_logs.txt)

**Comment by sachins-geekyants** [comment] 2023-01-05 12:37
Seems like after generating the atSign we are missing the first sync progress callback and app keeps showing `syncing` dialog box until some transactions happen because of other atSign and syncProgressListener is triggered again.

**Comment by gkc** [comment] 2023-01-05 16:46
Hi @sachins-geekyants  - next time you test, please can you run your app using at_client from my `gkc-log-the-atsign` branch?

```yaml
dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: gkc-log-the-atsign
```

Various classes will now log their atSigns when logging. This will make it easier to track down what's happening (which to me right now feels like a race condition related to usage of setCurrentAtSign)

**Comment by sachins-geekyants** [comment] 2023-01-06 08:52
Logs from running on `gkc-log-the-atsign`.

[gkc-monitor-log.odt](https://github.com/atsign-foundation/at_client_sdk/files/10358830/gkc-monitor-log.odt)

**Comment by gkc** [comment] 2023-01-06 11:12
@sachins-geekyants Thanks for the log. It shows
1. We switch atsigns from `@farebnursing34` to `@defeatedbanhxeo`
2. Sync for `@farebnursing34` is stopped
3. Sync for `@defeatedbanhxeo` is started and continues to run successfully
4. A little later when the monitor heartbeat timer for `@farebnursing34` runs, it determines that the monitor's status is stopped and therefore it shouldn't send a heartbeat.

This all _looks_ correct except for what you said re your syncProgressListener not being called, where there doesn't seem to be any logging

I've pushed another update to the branch so that `SyncServiceImpl._informSyncProgress` emits some FINER log messages. Can you run your test again where you are able to reproduce the syncProgressListener issue, and add the output here again please?

**Comment by gkc** [comment] 2023-01-08 00:36
I couldn't wait until the morning. Debugging the exception handling now. Problem reproduced, now diagnosing and then hopefully will fix.

**Comment by sachins-geekyants** [comment] 2023-01-10 10:45
Update: created a branch with merging `gkc-log-the-atsign` and `switch_atsign_bug` by Murali.  : `logger_with_switch_fix`

Tried generating new atsigns with and without saving backupkey.

[switch_atsign_log_sync_triggers_with_failure.odt](https://github.com/atsign-foundation/at_client_sdk/files/10381708/switch_atsign_log1_sync_triggers_with_failure.odt)


[switch_atsign_2_saving_backup_key.odt](https://github.com/atsign-foundation/at_client_sdk/files/10381699/switch_atsign_2_saving_backup_key.odt)


In both the cases sync progress was **triggering**, I could not reproduce the case where sync would not get trigger.

Another issue : In both the logs sync status is coming as failure -  it seems like an atSign activation issue happening in onboarding package : https://github.com/atsign-foundation/apps/issues/759

**Comment by sitaram-kalluri** [comment] 2023-01-17 07:46
Following bug https://github.com/atsign-foundation/at_server/issues/1136 is the potential cause of sync issue and activation issue. Spent 3SP in PR-53 to find the root cause of the issue.

**Comment by gkc** [comment] 2023-02-20 13:43
Closing as not reproducible

**Closed as completed by gkc** 2023-02-20 13:43 UTC
Labels: bug, 0 SP, PR53
