### ISSUE TITLE
pub.dev score badge error

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_client_sdk#689] opened 2022-09-06 14:27 UTC
**Describe the bug**
The pub.dev score badge on the readme.md file for at_client_mpbile is erroring (like a 404)

**To Reproduce**
Visit https://github.com/atsign-foundation/at_client_sdk/blob/trunk/at_client_mobile/README.md

**Comment by murali-shris** [comment] 2022-09-06 15:52
@nickelskevin we can make it a practise to check pub score before publishing
https://pub.dev/help/scoring
You can view your pub points report to get suggestions before publishing, by running pana locally:

When run pana will make modifications to the package, so start by making a copy of the directory holding your package: cp /dev/mypkg /tmp/mypkg

Make sure you have the latest pana tool: dart pub global activate pana (pana changes frequently, so run this again frequently to update the pana tool)

Run pana on the copy we made earlier: dart pub global run pana ~/tmp/mypkg

**Comment by purnimavenkatasubbu** [comment] 2022-09-09 05:49
Fix for the issue is available in PR #693. PR merged to trunk

**Comment by purnimavenkatasubbu** [comment] 2022-09-19 05:44
Closing the issue as the new version with the fix is published to pub.dev
[at_client](https://pub.dev/packages/at_client)

**Closed as completed by purnimavenkatasubbu** 2022-09-19 05:44 UTC
Labels: bug, documentation, Closed, 2 SP, Fixed, PR45
