### ISSUE TITLE
When using new atSigns and sshnpd/sshnp for the first time I see  errors in the logs

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#964] opened 2023-03-17 00:31 UTC
### Describe the bug

With new atSigns and using sshnp for the first time the sshnpd reports 

```
SEVERE|2023-03-16 17:24:03.690508|NotificationServiceImpl|Failed to fetchData caused by
Internal server exception : Request to remote secondary @cconstab at null:null received error response 'AT0015-Exception: @ssh_1:shared_key@cconstab does not exist in keystore'

SEVERE|2023-03-16 17:24:03.800266|NotificationServiceImpl|Failed to fetchData caused by
Internal server exception : Request to remote secondary @cconstab at null:null received error response 'AT0015-Exception: @ssh_1:shared_key@cconstab does not exist in keystore'
```

The second time and further times everything works just fine

### Steps to reproduce

1. Run sshnpd on remote machine and monitor logs
2. Then Iuse sshnp to remote in the first time it fails but once keys in place works fine.
4. And then check logs

### Expected behavior

No errors and works first time

### Smartphones

- Ubuntu at both ends

### Were you using an atApplication when the bug was found?

sshnp v 2.0.2

### Additional context

I was sure this was fixed, perhaps it is and I need to rebuild sshnp with new libs ? raising ticket to remind/have someone confirm

**Comment by cpswan** [comment] 2023-03-17 11:15
We should definitely be rebuilding binaries regularly to use our latest libraries (hence the need for greater automation).

Ideally:
* Pin dependencies - so that we know for sure that working binaries can be built from source
* Get dependabot to keep dependencies updated - so that we don't slip behind
* When those dependencies are updated build (and test) new binaries, to confirm that everything is working as expected.

We're already doing this for most of the key repos, but we need to do the same with projects like this (and frequently used demos).

**Comment by gkc** [comment] 2023-03-17 14:19
As best I can tell this issue does not occur with latest packages, because
1. Last release of sshnoports was on Dec 7 2022 ([PR](https://github.com/atsign-foundation/sshnoports/pull/49) and [GH action run](https://github.com/atsign-foundation/sshnoports/actions/runs/3641508305))
2. Fix for this issue was in at_client [version 3.0.49](https://pub.dev/packages/at_client/versions/3.0.49), published on Dec 12 2022

I will double-check that the issue _does_ occur when using at_client 3.0.48

**Comment by gkc** [comment] 2023-03-17 14:50
Confirmed the issue does occur every time when using at_client 3.0.48.

Using at_talk wound back to use at_client 3.0.48 and at_onboarding_cli 1.0.0, running newly-created alice and bob atServers locally
* first alice says 'hi bob'
* bob gets this:
    ```
    SEVERE|2023-03-17 14:38:23.760671|NotificationServiceImpl|Failed to fetchData caused by
    Internal server exception : Request to remote secondary @alice at null:null received error response
    'AT0015-Exception: @bob:shared_key@alice does not exist in keystore' 
    ```
* then bob says 'hi alice'
* and alice gets this
    ```
    SEVERE|2023-03-17 14:38:26.691418|NotificationServiceImpl|Failed to fetchData caused by
    Internal server exception : Request to remote secondary @bob at null:null received error response
    'AT0015-Exception: @alice:shared_key@bob does not exist in keystore' 
    ```

All subsequent requests in either direction work without issue

**Comment by gkc** [comment] 2023-03-17 14:50
Also (just for completeness) confirmed that the issue does not occur when using latest packages

**Closed as completed** 2023-03-17 15:14 UTC
Labels: bug
