### ISSUE TITLE
Automate doc published to prod and dev website

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#189] opened 2021-06-28 15:45 UTC
Update dart docs and when released gets updated on website

**Comment by cpswan** [comment] 2021-07-19 09:01
Is this a dupe of https://github.com/atsign-foundation/at_libraries/issues/77 and if not what's needed here that's not been done already?

**Comment by cpswan** [comment] 2021-07-21 12:46
Established to be a dupe - closing.

**Closed as completed by cpswan** 2021-07-21 12:46 UTC
Labels: 3 SP, PR15, PR16
