### ISSUE TITLE
Receiving multiple notifications instead of one

### ISSUE THREAD

**Issue by nitesh2599** [atsign-foundation/at_client_sdk#325] opened 2021-11-09 08:26 UTC
**Describe the bug**
When we send a notification from sender's side, we are receiving multiple notifications with different notification id.
Faced this in arrive and atmosphere pro.

**To Reproduce**
1. Log in to arrive and try sending a "share location" / "request location" / "create event"
2. On the receiver's side we get multiple notification 
3. This does not happen every-time but happens often.

**Expected behavior**
Receive one notification for each notification sent.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus (Simulator)
 - OS: iOS14.5

**Were you using an @‎application when the bug was found?**
  -Arrive and atmosphere pro ( Will not be re-producable on atmosphere pro as it is handled on the front end side)

**Additional context**
The notifications contained the same data and same frontend ID, but notification ID provided by the SDK was different for all versions of notifications received.
For "share location" / "request location" we used **put** calls and for "create event" we used **notifyAll**.
In atmosphere pro, we used **put** calls.

**Comment by DivyaYadavareddy** [comment] 2021-11-16 11:45
This issue is not appeared  while doing Request Location and Share Location. It appears in Create Event only. In my findings @31rudesardine5 sending an event to @6marvellousbat. sharedBy have 31rudesardine5 is fine but sharedwith has 6marvellousbat 2 times. beacuse of this 6marvellousbat  got notification 3 times.
Below attached screenshot
<img width="1440" alt="Screenshot 2021-11-16 at 12 35 49 PM" src="https://user-images.githubusercontent.com/60208911/141979635-a5f55057-5abc-452a-a1b7-03bb9f4af72d.png">

**Comment by DivyaYadavareddy** [comment] 2021-11-16 15:40
Need to know why ShareWith has multiple atsigns. Once the root cause is found, it will be fixed

**Comment by nitesh2599** [comment] 2021-11-16 15:55
@DivyaYadavareddy Thanks for noticing the multiple contacts in events, it was a bug from our side and we have fixed it now.

But, we faced the duplicate notifications issue in Share and Request location part. It is recorded in the request location part of this video at around 3: 20 https://drive.google.com/file/d/1MbynSmYsV7S4NCzMnDasVoAqRG_n5KcR/view

**Comment by DivyaYadavareddy** [comment] 2021-11-16 16:36
@nitesh2599  Can you please give me access to this video 
mailid: divya@atsign.com

**Comment by DivyaYadavareddy** [comment] 2021-11-22 06:25
@nitesh2599  Is this issue resolved ?? Can you please close this issue if it is resolved ??

**Comment by nitesh2599** [comment] 2021-11-22 06:59
@DivyaYadavareddy currently I am not facing this, lets keep it open for some time, if we still don't face it, I will close it.

**Closed as completed** 2021-11-29 08:16 UTC
Labels: bug, 3 SP, PR24, PR25
