### ISSUE TITLE
Get @ barbara's atsign working!

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_client_sdk#329] opened 2021-11-15 16:33 UTC
@nickelskevin or @sarika01 or @tinashe404  which ticket is this connected to, so we can mark here?  TY!

**Comment by sitaram-kalluri** [comment] 2021-11-22 06:11
The issue is because of bad data in the hive keystore. There is a key - "_no_smoke" which is triggering the exception during the construction of AtKey Object. Added a syntax check in atCommons package and a validation in at_client_sdk package which fixes the issue. 
Tested with barbara atsign and able to load persona after the fix.

**Comment by sitaram-kalluri** [comment] 2021-11-29 11:07
Published buzz to testflight - version: 1.1.6+45; 
Appstore - version -1.0.1;
Playstore - verison- 1.1.4+44

**Comment by purnimavenkatasubbu** [comment] 2021-11-29 12:33
Tested with the play store app. Personas are being loaded.
![1637834742343](https://user-images.githubusercontent.com/43639593/143868770-50b8c8f0-c1e2-4a58-b778-a787c1d47fdf.JPEG)

**Comment by sitaram-kalluri** [comment] 2021-11-29 12:36
@tallent : We are able to load the persona's for @barbara, Can you please test on the latest version of buzz app and confirm if we are good to close this issue?

**Closed as completed** 2021-11-29 16:11 UTC
Labels: 5 SP, Ready to test
