### ISSUE TITLE
provide validation around combined use of AtKey.sharedWith and Metadata.isPublic

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#366] opened 2021-12-21 14:20 UTC
**Is your feature request related to a problem? Please describe.**
AtKey.sharedWith is fully irrelevant when MetaData.isPublic is true. We lack validation / guidance to prevent this, and resulting behaviour is not determinable

**Describe the solution you'd like**
* When `isPublic == true` && `sharedWith != null`, either (a) throw an exception or (b) set isPublic to false and log a WARNING

This feature request is to improve behaviour for the existing API which will still be supported, although deprecated. 

Note that there is another feature request (#364) for a better API will also be provided which, if used, will avoid these potential bugs entirely.

**Comment by murali-shris** [comment] 2022-01-24 12:09
@gkc Work planned in this issue has been done as a part of
https://github.com/atsign-foundation/at_client_sdk/issues/373
Closing this one as duplicate

**Comment by murali-shris** [comment] 2022-01-24 12:10
duplicate of https://github.com/atsign-foundation/at_client_sdk/issues/373

**Closed as completed** 2022-01-24 12:10 UTC
Labels: enhancement, 2 SP
