### ISSUE TITLE
lookup on public key doesn't gives updated data.

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#455] opened 2022-03-28 12:31 UTC
**Describe the bug**
When we do a lookup for a public atkey, we get the value of the old cached key.

**To Reproduce**
1. create a public key with @ a 
2. try to fetch the key on @ b side
3. update the key from creator side(@ a)
4. fetch the key value again on @ b side, we get old cached data not the updated one.

**Expected behavior**
we should be getting the updated value on every lookup.

**Were you using an @‎application when the bug was found?**
  - @ mospherePro

**Additional context**
public key that I created
>   return AtKey()
      ..key = 'app_versions'
      ..metadata = Metadata()
      ..metadata!.isPublic = true
      ..sharedBy = '@significantredpanda';

**Comment by gkc** [comment] 2022-03-28 17:35
We discussed this today and agreed that in addition to the existing ability to use ttr where appropriate, we would implement an optional parameter for cached public key retrieval which, if set, will mean that we (1) always attempt to refresh from the remote secondary (2) if get successful response, replace the cached key or if not then (3) return the cached key we already had.

**Comment by sitaram-kalluri** [comment] 2022-04-04 11:21
On further discussion, Along with optional parameter(skip cache) it would be better to have tolerance which indicates the interval. Tolerance decides if the skip cache should be honoured or not. Discussion to continue

**Comment by sarika01** [comment] 2022-04-04 16:05
This was important to get version stored in public key. We have moved to github release tags to achieve the same.

**Comment by gkc** [comment] 2022-07-25 14:25
@murali-shris did we implement the `skip cache` feature?

**Comment by murali-shris** [comment] 2022-08-01 10:18
Duplicate of https://github.com/atsign-foundation/at_client_sdk/pull/591

**Closed as completed by murali-shris** 2022-08-01 10:18 UTC
Labels: bug, Architecture, PR33, PR34
