### ISSUE TITLE
at_client-3.0.4 Storage Manager argument issue

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_client_sdk#327] opened 2021-11-13 20:45 UTC
**Describe the bug**
Received this line when trying to Flutter Run:

```
../../../flutter/.pub-cache/hosted/pub.dartlang.org/at_client-3.0.4/lib/src/
    manager/storage_manager.dart:43:23: Error: Too many positional arguments: 1
    allowed, but 2 found.

  Try removing the extra positional arguments.
        await manager.init(currentAtSign, storagePath);
```

**To Reproduce**
1. Run command: `flutter run` on an application

**Expected behavior**
Could not build the application for the simulator.

**Screenshots**
<img width="569" alt="Screen Shot 2021-11-13 at 12 41 15 PM" src="https://user-images.githubusercontent.com/66637408/141658571-25251c49-1403-44f7-a5a9-2af40b0c6d41.png">

**Smartphone (please complete the following information):**
Emulator - Iphone 13 Pro

**Comment by yahu1031** [comment] 2021-11-13 22:41
@TylerTrott Use `dependency_overrides:` in pubspec.yaml file for time being as follows.

```yaml
dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      ref: trunk
      path: at_client
```
This will resolve the issue for now. And this can be fixed on next release.

**Comment by yahu1031** [comment] 2021-11-13 22:44
This issue is because [at_persistence_secondary_server](https://pub.dev/packages/at_persistence_secondary_server) has been released before the [at_client](https://pub.dev/packages/at_client) package release. And the latest changes regarding that are on the git repository in the `trunk` branch. Please make use of it.

**Comment by cconstab** [comment] 2021-11-13 22:51
If you prefer to stick with the previous version (I did) then for the moment at least, specify this in the dependencies section of pubspec.yaml.. Once we have this fixed you can obviously remove and then run `flutter pub get` 
This will get your code working as it was yesterday..

```
 dependencies:
  at_persistence_secondary_server: 3.0.5
  at_persistence_spec: 2.0.1
  
```

**Comment by murali-shris** [comment] 2021-11-15 09:28
@TylerTrott latest version of persistence needs latest version of at_client. We will publish at_client today.Until then please use the old version of persistence

**Comment by sitaram-kalluri** [comment] 2021-11-15 10:19
@TylerTrott : The issue is fixed and published. Please use at_client: ^3.0.5.

**Closed as completed** 2021-11-15 10:35 UTC
Labels: bug, 1 SP
