### ISSUE TITLE
collections test in e2e test pack is flaking, failing frequently

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#1091] opened 2023-07-18 08:21 UTC
### Describe the bug

in collection_test.dart: "Model operations - save() with reshare() as true test" is failing frequently, requiring re-runs of the e2e test pack

### Steps to reproduce

See https://github.com/atsign-foundation/at_client_sdk/actions/runs/5584776526/jobs/10207089878 for example

```
❌ test/collection_test.dart: Model operations - save() with reshare() as true test (failed)
  INFO|2023-07-18 08:15:54.007871|AtLookup|Creating new connection 
  
  INFO|2023-07-18 08:15:54.191342|AtLookup|New connection created OK 
  
  INFO|2023-07-18 08:15:54.395353|AtLookup|auth success 
  
  INFO|2023-07-18 08:15:54.494525|SyncService (@ce2e2)|192496788|Returning serverCommitId 312115 
  
  INFO|2023-07-18 08:15:54.50[158](https://github.com/atsign-foundation/at_client_sdk/actions/runs/5584776526/jobs/10207089878#step:8:160)0|SyncService (@ce2e2)|192496788|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.app; syncRequest.onDone : null 
  
  Expected: <0>
    Actual: <1>
  On the recipient side expecting a single keys with the regex supplied
  
  package:matcher                  expect
  test/collection_test.dart 305:5  main.<fn>
```

### Expected behavior

test should pass

**Comment by gkc** [comment] 2023-07-18 08:47
Failed again in this test run https://github.com/atsign-foundation/at_client_sdk/actions/runs/5584776526/jobs/10207763726

**Comment by purnimavenkatasubbu** [comment] 2023-07-18 08:49
I was able to replicate the test failure locally after multiple tries. Client logs show a sync failure. Looking at server logs for more clues

SEVERE|2023-07-18 14:02:55.085840|AtLookup|Exception in sending to server, Exception: Waited for 10000 millis. No response after 2023-07-18 14:02:42.369355  

SEVERE|2023-07-18 14:02:55.086943|AtLookup|Error in remote verb execution Exception: Waited for 10000 millis. No response after 2023-07-18 14:02:42.369355  

SEVERE|2023-07-18 14:02:55.088203|SyncUtil|Exception while getting latest server commit id: Exception: Exception: Waited for 10000 millis. No response after 2023-07-18 14:02:42.369355  

SEVERE|2023-07-18 14:02:55.089987|SyncService (@ce2e2)|Exception in sync 326e7b31-3256-4782-9dc8-631dbe4bba5d. Reason: Failed to syncData caused by
Unable to fetch latest server commit id: Exception: Exception: Waited for 10000 millis. No response after 2023-07-18 14:02:42.369355  

INFO|2023-07-18 14:02:55.090454|E2ESyncService|Completed sync for @ce2e2| SyncStatus.failure | localCommitId: null | ServerCommitId: null | Processing time: 12730 millis

**Comment by gkc** [comment] 2023-07-18 09:13
Thank you @purnimavenkatasubbu! @VJag @sitaram-kalluri I think there are many records in our e2e atsigns' commit logs ... I wonder if these timeouts would be remedied by the performance fix you mentioned yesterday?

**Comment by gkc** [comment] 2023-07-29 13:52
This is failing very frequently (read: requires a re-run pretty much every time) and having to manually trigger re-runs (sometimes more than once) is wasting a lot of time.

**Comment by gkc** [comment] 2023-07-30 11:29
another failed run [here](https://github.com/atsign-foundation/at_client_sdk/actions/runs/5705914011/job/15461067472)

**Comment by sitaram-kalluri** [comment] 2023-07-31 03:38
@gkc: Looking into this issue.

**Comment by gkc** [comment] 2023-08-02 10:14
Problem is still occurring. See examples
- https://github.com/atsign-foundation/at_client_sdk/actions/runs/5736590366/job/15546506053 from this morning
- https://github.com/atsign-foundation/at_client_sdk/actions/runs/5735991813/job/15544714736 from this morning
- https://github.com/atsign-foundation/at_client_sdk/actions/runs/5725435274/job/15513952967 from yesterday

In each case, the test run failed the first time and succeeded on re-run

**Comment by sitaram-kalluri** [comment] 2023-08-03 07:38
> Problem is still occurring. See examples
> 
> * https://github.com/atsign-foundation/at_client_sdk/actions/runs/5736590366/job/15546506053 from this morning
> * https://github.com/atsign-foundation/at_client_sdk/actions/runs/5735991813/job/15544714736 from this morning
> * https://github.com/atsign-foundation/at_client_sdk/actions/runs/5725435274/job/15513952967 from yesterday
> 
> In each case, the test run failed the first time and succeeded on re-run

The issue is addressed in the PR: https://github.com/atsign-foundation/at_client_sdk/pull/1103

**Comment by sitaram-kalluri** [comment] 2023-08-07 05:24
In PR-67, PR: 1103 is merged to trunk branch and mostly likely the issue will not resurface again.

**Closed as completed** 2023-08-07 06:11 UTC
Labels: bug
