### ISSUE TITLE
Synchronisation error - Invalid or corrupted pad block

### ISSUE THREAD

**Issue by ralfeus** [atsign-foundation/at_client_sdk#749] opened 2022-10-12 05:28 UTC
### Describe the bug

Sometimes after key creation the synchronisation fails with following error:
```
I/flutter (30031): SEVERE|2022-10-11 02:54:02.704061|EncryptionUtil|Error while decrypting value: Invalid argument(s): Invalid or corrupted pad block
I/flutter (30031): SEVERE|2022-10-11 02:54:02.708559|NotificationServiceImpl|Failed to decryptData caused by
I/flutter (30031): Failed to decrypt @baboon9blue:@baboon9blue:shared_key@81bored7@81bored7 caused by
I/flutter (30031): Invalid argument(s): Invalid or corrupted pad block
```

No further indication of the error

### Steps to reproduce

1. Create a key and put it to local storage
2. Have keys synchronized

### Expected behavior

Keys are synchronised as they are

### Smartphones

- Device: Emulator
- OS: Android

### Were you using an atApplication when the bug was found?

None

**Comment by purnimavenkatasubbu** [comment] 2022-10-18 09:37
From the logs, the shared_key has been appended by the atsigns twice.( @baboon9blue:@baboon9blue and @81bored7@81bored7) which is incorrect.

The correct syntax of the key is as follows
![Screenshot from 2022-10-18 13-54-05](https://user-images.githubusercontent.com/43639593/196394341-6af09aa2-697b-4e08-a5c5-59dcd10814ea.png)

Here murali is the sharedWIth atsign and sitaram is the sharedBy atsign

**Comment by sitaram-kalluri** [comment] 2022-10-18 14:47
**Root cause of the issue:**  

On the sender side, a sharedKey (AES key) is generated and is encrypted with the receiver's public key and the resultant which is encryptedSharedKey is notified to the receiver's atsign. On the receiver side, when a notification related to sharedKey arrives, it is treated a SharedKey and SharedKeyDecryption is performed; which means the encryptedSharedKey is decrypted with the original sharedKey which leads to the corrupted pad block error.

Below is the screenshot which show the encryptedValue and the encryptedSharedKey has a same value.

![image](https://user-images.githubusercontent.com/16645698/196463250-803188d2-9ed4-4577-9ef6-e019c274e63b.png)

**Comment by sitaram-kalluri** [comment] 2022-10-26 04:58
The issue is fixed and changes are merged to trunk branch

**Comment by sitaram-kalluri** [comment] 2022-10-28 06:14
The changes are published in v3.0.42. Hence marking the issue as fixed.

**Comment by gkc** [comment] 2022-10-31 02:39
Thanks @kalluriramkumar ... did you look into why the error message says `Failed to decrypt @baboon9blue:@baboon9blue:shared_key@81bored7@81bored7` instead of `Failed to decrypt @baboon9blue:shared_key@81bored7` ?

**Comment by sitaram-kalluri** [comment] 2022-10-31 02:56
> Thanks @kalluriramkumar ... did you look into why the error message says `Failed to decrypt @baboon9blue:@baboon9blue:shared_key@81bored7@81bored7` instead of `Failed to decrypt @baboon9blue:shared_key@81bored7` ?

Yes, @gkc. In the update_verb_handler.dart, we prefix and append the sharedWith and sharedBy to the key before sending the notification. So, the key in the notification looks like "@‎bob:phone@alice"; when logging the key, we have an atKey.toString which will again add sharedWith and sharedBy to the key. Hence the atsign's are shown twice.

**Comment by gkc** [comment] 2022-10-31 02:58
Great - have you created a ticket to track fixing that bug?

**Comment by sitaram-kalluri** [comment] 2022-10-31 03:00
> Great - have you created a ticket to track fixing that bug?

I remember seeing a similar bug. I will go through the bugs list. If there is no issue, will create one and update the git issue here.

**Comment by sitaram-kalluri** [comment] 2022-10-31 03:19
> Thanks @kalluriramkumar ... did you look into why the error message says `Failed to decrypt @baboon9blue:@baboon9blue:shared_key@81bored7@81bored7` instead of `Failed to decrypt @baboon9blue:shared_key@81bored7` ?

Created a git issue to the bug: https://github.com/atsign-foundation/at_client_sdk/issues/772

**Comment by gkc** [comment] 2023-02-20 13:39
Closing this ticket as fixed. There is another issue with decryption reported by @ralfeus which I will be looking into this week

**Closed as completed by gkc** 2023-02-20 13:39 UTC
Labels: bug, 3 SP, Fixed, PR48
