### ISSUE TITLE
Stream ack call failing due to encryption

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_client_sdk#110] opened 2021-04-07 08:31 UTC
The file transfer in atmosphere basic app is failing due to encryption issue. The file transfer request is received correctly and upon acknowledging, the call fails in the receiver's end.
<img width="1432" alt="Screenshot 2021-04-07 at 1 58 51 PM" src="https://user-images.githubusercontent.com/12222326/113835570-b2cd5380-97a9-11eb-8ba7-e5c2533eba70.png">

**Comment by sarika01** [comment] 2021-04-07 08:33
After failing to receive, it fails to send file as well.
<img width="1431" alt="Screenshot 2021-04-07 at 2 02 20 PM" src="https://user-images.githubusercontent.com/12222326/113835862-f627c200-97a9-11eb-8903-3885674d833e.png">

**Comment by sarika01** [comment] 2021-04-15 10:02
Issue is resolved with the latest code on dev_env branch.

**Comment by sarika01** [comment] 2021-04-15 10:31
Encountered it again with the same code after a few restart of the app.

![Uploading Screenshot 2021-04-15 at 4.00.51 PM.png…]()

**Comment by naresh0689** [comment] 2021-04-21 17:02
Not able to reproduce the issue. @sarika01 Could you please try again and let us know the steps to reproduce.

**Comment by murali-shris** [comment] 2021-06-28 13:04
Closing the issue since it is no longer reproducible

**Closed by murali-shris** 2021-06-28 13:04 UTC
Labels: 3 SP, PR10, PR11, PR13, PR14, PR9, bug
