### ISSUE TITLE
Error in put: FormatException

### ISSUE THREAD

**Issue by nitesh2599** [atsign-foundation/at_client_sdk#69] opened 2021-03-08 10:24 UTC
Getting these AtClientImpl exception sometimes while sending a notification (in put method) while running in virtual environment .

![Screenshot 2021-03-08 at 2 40 06 PM](https://user-images.githubusercontent.com/74917928/110308526-3f0f1e00-8026-11eb-8d34-4a343404e971.png)

![Screenshot 2021-03-08 at 2 40 22 PM](https://user-images.githubusercontent.com/74917928/110308556-4afae000-8026-11eb-98bf-ee1451bd0282.png)

**Comment by nitesh2599** [comment] 2021-03-08 14:37
Also facing it in staging

**Comment by sarika01** [comment] 2021-04-08 06:10
Still facing the issue. Need to retest when ability to open multiple outbound connections is provided.

**Comment by naresh0689** [comment] 2021-06-16 09:46
Not able to reproduce the issue.
Verified with @nitesh2599  as well. After dedicated connection changes in at_client_sdk, they are not facing this issue. 
We will close the issue once changes are available in master and published to pub.dev.

**Closed** 2021-06-28 13:11 UTC
Labels: 3 SP, PR14, bug
