### ISSUE TITLE
Encrypted Shared key not found

### ISSUE THREAD

**Issue by nitesh2599** [atsign-foundation/at_client_sdk#358] opened 2021-12-16 10:32 UTC
Lead: @kalluriramkumar

**Describe the bug**
For all notifications sent from 'minorgettingplayed7'  to 'amateurduma94', the decryption fails with the exception:
"Exception: encrypted Shared key not found"

**To Reproduce**
1. Log in with 'minorgettingplayed7' and 'amateurduma94' on the arrive app.
2. Send a 'Share Location' notification from 'minorgettingplayed7' to 'amateurduma94'.
3. On 'amateurduma94's side, we should get the above exception.

**Expected behavior**
Decryption should be successful.

**Screenshot**
<img width="781" alt="Screenshot 2021-12-16 at 3 55 54 PM" src="https://user-images.githubusercontent.com/74917928/146354378-ce1c4400-9cb4-4e63-9a6a-432aae27d2a5.png">

**Smartphone :**
 - Device: 'minorgettingplayed7' on iPhone 11 simulator & 'amateurduma94' on iPhone 8 simulator
 - OS: iOS 14.5

**Were you using an @‎application when the bug was found?**
 - arrive

**Additional context**
'amateurduma94' is able to send 'minorgettingplayed7' notifications

**Comment by yahu1031** [comment] 2022-01-10 22:08
Looks like this is fixed in [#atsign-foundation/apps#391](https://github.com/atsign-foundation/apps/issues/391)

**Comment by nitesh2599** [comment] 2022-01-11 12:37
#atsign-foundation/apps#391 this is only a front end fix where we show a toast of why the decryption has failed.

**Comment by yahu1031** [comment] 2022-01-11 13:02
okie, I will look into it then.

**Comment by gkc** [comment] 2022-01-21 11:07
@yahu1031 any progress on this?

**Comment by yahu1031** [comment] 2022-01-21 11:08
@gkc not yet Gary. I will work on it.

**Comment by yahu1031** [comment] 2022-01-31 06:24
I see `minorgettingplayed7:shared_key@@amateurduma94`. It has 2 `@`.

**Comment by gkc** [comment] 2022-02-07 13:11
@yahu1031 @murali-shris  What are the next steps here?

**Comment by yahu1031** [comment] 2022-02-07 13:19
Well, I spent 3SP on this issue, and the next few days I was on leave. Some changes have been done in SDK and deployed to canary it seems. I request @nitesh2599 to recheck/ try reproducing this issue. If it still exists, I would like to continue on the upcoming sprint. I tested this issue today but couldn't reproduce it.

**Additional context (atSigns Location)**
amateurduma94 - hornet
minorgettingplayed7 - canary

- When I pinged @nitesh2599 on this issue, He mentioned this issue is with `minorgettingplayed7`. So I request you to recheck this once again.
- If this is still reproducible, I would like to have 5SP

**Comment by nitesh2599** [comment] 2022-02-07 14:10
@yahu1031 I can still see the issue.
<img width="730" alt="Screenshot 2022-02-07 at 7 37 41 PM" src="https://user-images.githubusercontent.com/74917928/152803673-3a44e6e6-d576-4435-bceb-8bc6f7bdd03b.png">

**Comment by yahu1031** [comment] 2022-02-07 14:18
cool, I will continue investigating this.

**Comment by yahu1031** [comment] 2022-02-07 15:20
Maybe I need 3SP or 5SP in this sprint.

**Comment by gkc** [comment] 2022-02-07 16:42
Since this is related to encryption / decryption and has been open for ~8 weeks, I'm going to mark this P1

**Comment by gkc** [comment] 2022-02-18 16:00
@yahu1031 please can you update this ticket so it's up to date for the sprint planning on Monday

**Comment by sitaram-kalluri** [comment] 2022-02-21 04:32
Connected via the open-ssl to the remote secondary of `minorgettingplayed7` does not have the shared_key created for the `amateurduma94`. Hence the issue. The potential cause is the shared_key not sync'ed to the remote secondary of 'minorgettingplayed7'. However, with recent changes the sync and notification are more reliable that would prevent the issue.

**Comment by sitaram-kalluri** [comment] 2022-02-21 07:18
approach: Extend metadata to include encryptionKey/sharedKey and publicKeyChecksum

Description:
Let's say @ jagan wants to share the phone with @ sitaram (@ sitaram:phone@jagan), details look like this.


Meta:
	ttl:
	ttb:
	ccd:
	encryptionKey/sharedKey: <AES key encrypted with @ sitaram's public key>
	publicKeyChecksum: <Checksum of Sitaram's public key at the time of encryption>


Data: <Data encrypted for @ sitaram using an AES key shared in the metadata>

@ sitaram:phone@jagan

currPk - Pk2  ~   oldPk - Pk1
notify jagan a re-share

Advantages:
1. Data carries the original footprint of the encryption keys which means if you have one key it should be enough to decrypt
2. We have a way to compare the old public key with the new public key

Dis-advantages:
1. Bigger footprint of the data

**Comment by sitaram-kalluri** [comment] 2022-02-21 14:57
Analysis on potential causes of exceptions on decrypting the data:

1. When an atsign is logged into two different devices:
	When the same atsign is onboarded on two different devices. When a key is created and shared to the same atsign from the two devices, since initially, the shared_key does not exist, both devices create two different shared keys. When synced to remote secondary, the former shared_key would be overridden by the latter causing the issue when decryption the data.
2. Delay in sync: ( + Switch @ sign before sync) 
	When data is notified (key not created on sender side) with TTR Since notify is a direct call to remote secondary, this happens immediately and cached key will be created on the receiver end. On the flip side, sync triggers only when a sync threshold is met. when shared_key is created, if the sync threshold is not met, the shared_key would not be synced to remote secondary thus causing encryption shared key not found while decrypting.
3. Key Creation during full sync:
	When an atsign with lots of commit Id's is onboarded; If the shared_key is created even before the initial sync is completed, it may not sync the shared_key to the remote secondary. The keys that are created after the initial sync will be synced to remote secondary. Since the shared_key is not synced to remote secondary, on the decryption side a shared_key not found error occurs.

**Comment by VJag** [comment] 2022-02-21 15:16
We will solve some of the issues once we implement:

1. Sync progress listener to prevent an update before full sync on app side
2. Validations are plugged in during key creation in SDK

However, we still need the approach discussed above to solve other problems.

**Comment by murali-shris** [comment] 2022-03-07 06:45
Code changes done in sharedkey_metadata across repos and PRs currently under review.
I am looking into an issue reported by Purnima..
Moving this issue to next sprint. pending tasks - testing and publishing packages

**Comment by murali-shris** [comment] 2022-03-21 13:15
server 3.0.13 released to production

**Closed as completed by murali-shris** 2022-03-21 13:15 UTC
Labels: bug, 5 SP, P1, PR29, PR30, PR31, PR32
