### ISSUE TITLE
at_client_mobile integrate at_auth

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#1140] opened 2023-10-16 11:36 UTC
### Is your feature request related to a problem? Please describe.

* at_client_mobile has code duplication with at_onboarding_cli

### Describe the solution you'd like

* duplicate code has been moved to at_auth package
* integrate at_auth changes with at_client_mobile

**Comment by sitaram-kalluri** [comment] 2023-10-30 12:48
Work done in PR:73 - at_auth package changes are uptaken into the at_client_mobile and the changes are available in the [apkam_onboarding_changes](https://github.com/atsign-foundation/at_client_sdk/tree/apkam_onboarding_changes). 

Pending work in PR-74 : Review the code changes and raise a PR.

**Comment by sitaram-kalluri** [comment] 2023-11-14 12:18
Spent 8 SP in PR-74

The enrollment changes that are common between the "at_onboarding_flutter" for UI and "at_onboarding_cli" are moved to AtAuth package. The corresponding changes in at_client_mobile are completed and pushed to "apkam_onboarding_changes". 

The changes are tested and a recording is attached in the following git issue: https://github.com/atsign-foundation/operations/issues/88

Pending work is to raise a PR and publish the package.

**Comment by sitaram-kalluri** [comment] 2023-11-27 02:28
Spent 5 SP in PR-75.

- Tested the changes with enrollment app. where the enrollment is being submitted and able to generate .keys file upon approval.
- Pending work is to test the the changes with existing app for regression. Currently, blocked on this because "wavi" app fails to build in local. Updated the issue in "Engg. Chat threads channel" and requested @sachins-geekyants  help in resolving the issue.

**Comment by sitaram-kalluri** [comment] 2023-12-11 06:17
Spent 3 SP in PR-76
- Tested the at_auth package changes with wavi app and buzz app and able to onboard the atsign successfully.

**Comment by murali-shris** [comment] 2024-01-22 10:49
Awaiting APKAM uptake in apps for merging and publishing

**Comment by sitaram-kalluri** [comment] 2024-04-02 10:50
Published the at_auth package. at_auth v1.0.6 has the changes related to APKAM

**Comment by sitaram-kalluri** [comment] 2024-04-15 13:38
The changes are completed and are merged to trunk branch in at_client_mobile in the PR: https://github.com/atsign-foundation/at_client_sdk/pull/1257. Hence closing the issue.

**Closed as completed by sitaram-kalluri** 2024-04-15 13:38 UTC
Labels: enhancement
